dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
addons: 
  apt: 
    packages: 
      - google-chrome-stable
    sources: 
      - google-chrome
  sonarcloud: 
    organization: worriedhugo-github
    token: 
      secure: $SONAR_TOKEN_ICARUS

jdk:
  - oraclejdk8

cache:
  directories:
     - ./node_modules
     - '$HOME/.sonar/cache'

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - sonar-scanner