language: node_js
node_js:
  - "node"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost:4200` based on what you have here[2]
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
